### ISSUE TITLE
Server will hang if there are pod use nfs when enable contiv-vpp cni

### ISSUE THREAD

**Issue by LipingMao** [contiv/vpp#1461]
when k8s enabled contiv-vpp, and there are other pods which mount nfs. The problem is when reboot/shutdown the node, pods will shutdown and umount, vpp may stop before the pod which mount nfs. in that case, the pod get lost to the nfs server. Then it will hang in umount nfs. and report the following error:
nfs: server (XXX) not responding, still trying...

This maybe break the files in nfs store.

**Comment by rastislavszabo** [comment]
Does the application properly hande SIGTERM signal?

I don't see how this can be fixed in Contiv-VPP. The actual order of killing PODs when shutting down is on Kubernetes. It should first send SIGTERM to each POD and give them some time (I guess 30 seconds) to exit nicely, then kills them with SIGKILL.

VPP will exit as soon it receives SIGTERM from kubernetes.

**Comment by LipingMao** [comment]
Thanks for your reply, @rastislavszabo . 

when app pod umount nfs , it need to connect to nfs server, the problem if the vpp pod stop first, the app pod will lost network immeditaly, it is possible to let nfs timeout in short time. But nfs data may be lost. 

Looks like there is no shutdown order when kill pods. In the case, pod use kernel network cni, it works,  kernel network stack still work. But in the case of vpp, network datapath itself become a pod, it better to have order. when VPP pod stop, all the pod will lost network connection.

Right now, I'm using reduce JobTimeoutSec in reboot.target.  I'm not sure if there is better way or community has any idea about this kind of issue.
/usr/lib/systemd/system/reboot.target:JobTimeoutSec

**Comment by rastislavszabo** [comment]
Not a Contiv-VPP issue.
