### ISSUE TITLE
contiv-vpp performance issue for host to nodeport

### ISSUE THREAD

**Issue by acloudiator** [contiv/vpp#944]
Hi Folks,

I'm running a small performance test with contiv-vpp to measure the bandwidth and throughput using the iperf3.

- Looks like the throughput I am getting is less than 4 Gbits/sec for `host to nodeport (same node)` and less than 1 Mbits/sec for `host to nodeport (different node)` for my 25 GbE NIC (Intel XXV710 SFP)
- It's a simple iperf3 setup on each node and NodePort service configured for each of them.

Anybody trying to do some performance testing or can help to confirm in their environment? Thanks!

**Comment by jmedved** [comment]
You 1MBit/s or 1 GBit/s? 

Also, if you haven't done so, please remove the line '    poll-sleep-usec 100' from vpp configuration (/etc/vpp/contiv-vswitch.conf) - that's there for VM deployments, and will impact performance.

**Comment by rastislavszabo** [comment]
Hi,
measuring the performance *from host* is not really a good way to benchmark contiv-vpp. It means that all NATing happens in the kernel (via iptables rules installed by kube-proxy). Try measuring from POD (NOT with hostNetwrok==True), that way all NATing happens on VPP.

**Comment by acloudiator** [comment]
So, I tried  **pod to pod (two different nodes)** case, and the bandwidth at receiver end is `0.00 bits/sec`, whereas,  sender send out merely `69.5 Kbits/sec` for the test of 10 seconds over 25GbE NIC.

Details are as follows:
```
NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE       IP          NODE
default       pod/iperf3-node1-clusterip                1/1       Running   0          17h       10.1.1.4    al-server-a
default       pod/iperf3-node2-clusterip                1/1       Running   0          17h       10.1.2.6    al-blacknode-a
kube-system   pod/contiv-etcd-0                         1/1       Running   0          17h       1.2.3.10    al-server-a
kube-system   pod/contiv-ksr-rssb6                      1/1       Running   0          17h       1.2.3.10    al-server-a
kube-system   pod/contiv-vswitch-6lckm                  1/1       Running   0          17h       1.2.3.10    al-server-a
kube-system   pod/contiv-vswitch-k7s4k                  1/1       Running   0          17h       1.2.3.100   al-blacknode-a
kube-system   pod/coredns-78fcdf6894-g65m9              1/1       Running   220        17h       10.1.2.2    al-blacknode-a
kube-system   pod/coredns-78fcdf6894-s68zv              1/1       Running   219        17h       10.1.2.3    al-blacknode-a
kube-system   pod/etcd-al-server-a                      1/1       Running   0          17h       1.2.3.10    al-server-a
kube-system   pod/kube-apiserver-al-server-a            1/1       Running   0          17h       1.2.3.10    al-server-a
kube-system   pod/kube-controller-manager-al-server-a   1/1       Running   0          17h       1.2.3.10    al-server-a
kube-system   pod/kube-proxy-drcxj                      1/1       Running   0          17h       1.2.3.10    al-server-a
kube-system   pod/kube-proxy-g5rcx                      1/1       Running   0          17h       1.2.3.100   al-blacknode-a
kube-system   pod/kube-scheduler-al-server-a            1/1       Running   0          17h       1.2.3.10    al-server-a
```

**Testing as a client:**
```
$ kubectl exec iperf3-node1-clusterip -- iperf3 -c 10.1.2.6 -p 5201
Connecting to host 10.1.2.6, port 5201
[  4] local 10.1.1.4 port 58478 connected to 10.1.2.6 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  84.8 KBytes   694 Kbits/sec    2   1.41 KBytes
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes
[  4]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes
[  4]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes
[  4]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  84.8 KBytes  69.5 Kbits/sec    5             sender
[  4]   0.00-10.00  sec  0.00 Bytes  0.00 bits/sec                  receiver

iperf Done.
```

Message from iperf3 server:
```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
get_parameters:
{
	"tcp":	true,
	"omit":	0,
	"time":	10,
	"parallel":	1,
	"len":	131072
}
Time: Fri, 20 Jul 2018 20:57:06 GMT
Accepted connection from 10.1.1.4, port 59626
      Cookie: iperf3-node1-clusterip.1532120226.43
      TCP MSS: 1448 (default)
[  5] local 10.1.2.6 port 5201 connected to 10.1.1.4 port 59628
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
[  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec
tcpi_snd_cwnd 10 tcpi_snd_mss 1448
get_results
{
	"cpu_util_total":	0.41101,
	"cpu_util_user":	0.0821426,
	"cpu_util_system":	0.328898,
	"sender_has_retransmits":	1,
	"streams":	[{
			"id":	1,
			"bytes":	86880,
			"retransmits":	5,
			"jitter":	0,
			"errors":	0,
			"packets":	0
		}]
}
send_results
{
	"cpu_util_total":	0.00226738,
	"cpu_util_user":	0.0022252,
	"cpu_util_system":	4.04991e-05,
	"sender_has_retransmits":	-1,
	"streams":	[{
			"id":	1,
			"bytes":	0,
			"retransmits":	-1,
			"jitter":	0,
			"errors":	0,
			"packets":	0
		}]
}
[  5]  10.00-10.03  sec  0.00 Bytes  0.00 bits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  5]   0.00-10.03  sec  84.8 KBytes  69.3 Kbits/sec    5             sender
[  5]   0.00-10.03  sec  0.00 Bytes  0.00 bits/sec                  receiver
CPU Utilization: local/receiver 0.0% (0.0%u/0.0%s), remote/sender 0.4% (0.1%u/0.3%s)
iperf 3.0.7
```

**IP route from client:**
```
al-server-a:~$ ip route get 10.1.2.6
10.1.2.6 via 2.2.3.1 dev vpp1 src 2.2.3.10 uid 1003
    cache
```

**Ping from VPP (client to iperf3 server):**
```
al-server-a:~$ sudo vppctl ping 10.1.2.6
64 bytes from 10.1.2.6: icmp_seq=1 ttl=63 time=.5222 ms
64 bytes from 10.1.2.6: icmp_seq=2 ttl=63 time=.4073 ms
64 bytes from 10.1.2.6: icmp_seq=3 ttl=63 time=.5462 ms
64 bytes from 10.1.2.6: icmp_seq=4 ttl=63 time=.5253 ms
64 bytes from 10.1.2.6: icmp_seq=5 ttl=63 time=.5433 ms

Statistics: 5 sent, 5 received, 0% packet loss
```

**Ping from VPP (iperf3 server to client):**
```
al-blacknode-a:~$ sudo vppctl ping 10.1.1.4
64 bytes from 10.1.1.4: icmp_seq=1 ttl=63 time=.5044 ms
64 bytes from 10.1.1.4: icmp_seq=2 ttl=63 time=.5138 ms
64 bytes from 10.1.1.4: icmp_seq=3 ttl=63 time=.3973 ms
64 bytes from 10.1.1.4: icmp_seq=4 ttl=63 time=.3868 ms
64 bytes from 10.1.1.4: icmp_seq=5 ttl=63 time=.5670 ms

Statistics: 5 sent, 5 received, 0% packet loss
```

**Comment by acloudiator** [comment]
Hi @rastislavszabo any comments/suggestions? Do you have the same issue in your lab?

**Comment by jmedved** [comment]
Hi @acloudiator, you are pinging from VPP to a remote pod, not from pod to pod. Something is not right with your network topology, and end-to-end pod-to-pod connectivity does not seem to be working. Can you please run the 'contiv-vpp-bug-report.sh' script on your cluster and send us the resulting zip file? 

I do not ha ve a bare metal setup, but i ran iperf on my VM setup that I brought up using our Vagrant scripts (VirtualBox on Linux16.04). Everything worked fine. Can you please try it yourself on a vagrant setup, and see if it works for you? Thanks.

**Comment by Rychne** [comment]
Hi,
i ran into the same issue, im trying to measure the performance on both the bare metal and the vagrant setup. The tests on the vagrant setup are working fine, but on the bare metal setup i got results as above. 

pod-to-pod connectivity seems working for me. 
### Ping from  10.1.2.9 to a pod on a different node
```
root@scapy:/# ping 10.1.3.7
PING 10.1.3.7 (10.1.3.7) 56(84) bytes of data.
64 bytes from 10.1.3.7: icmp_seq=2 ttl=62 time=0.475 ms
64 bytes from 10.1.3.7: icmp_seq=3 ttl=62 time=0.876 ms
64 bytes from 10.1.3.7: icmp_seq=4 ttl=62 time=0.635 ms
64 bytes from 10.1.3.7: icmp_seq=5 ttl=62 time=0.764 ms
64 bytes from 10.1.3.7: icmp_seq=6 ttl=62 time=0.719 ms
```

Here is the zip from the contiv-bug-report script:
[contiv-vpp-bug-report-2018-07-25-15-44.tar.zip](https://github.com/contiv/vpp/files/2228180/contiv-vpp-bug-report-2018-07-25-15-44.tar.zip)

**Comment by jmedved** [comment]
Hi,
can you please share the Linux version being run on the bare metal setup, the deployment yamls for the netperf daemonsets, and the commands/scripts used to perform the test? Are you running netperf against the physical addresses of the netperf pods, or against the netperf-server service address (10.110.227.44)? Thx.

**Comment by gilesheron** [comment]
this isn't some strange fragmentation problem, is it?  MSS of 1448 will be too big for 1500 byte packets once you account for the VXLAN overhead.

at any rate will try to test here on my own bare metal setup

**Comment by gilesheron** [comment]
ok works fine for me:

xrvr@i2ss-c2201:~$ kubectl exec iperf3-clients-cfrvc -- iperf3 -c 10.1.2.8 -p 5201
Connecting to host 10.1.2.8, port 5201
[  4] local 10.1.2.9 port 40764 connected to 10.1.2.8 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   158 MBytes  1.32 Gbits/sec   55    369 KBytes       
[  4]   1.00-2.00   sec   182 MBytes  1.53 Gbits/sec   39    359 KBytes       
[  4]   2.00-3.00   sec   164 MBytes  1.38 Gbits/sec   10    332 KBytes       
[  4]   3.00-4.00   sec   158 MBytes  1.32 Gbits/sec    4    407 KBytes       
[  4]   4.00-5.00   sec   153 MBytes  1.28 Gbits/sec   14    303 KBytes       
[  4]   5.00-6.00   sec   168 MBytes  1.41 Gbits/sec   21    334 KBytes       
[  4]   6.00-7.00   sec   159 MBytes  1.33 Gbits/sec   12    283 KBytes       
[  4]   7.00-8.00   sec   153 MBytes  1.29 Gbits/sec    9    404 KBytes       
[  4]   8.00-9.00   sec   135 MBytes  1.13 Gbits/sec   17    335 KBytes       
[  4]   9.00-10.00  sec   138 MBytes  1.16 Gbits/sec    6    399 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.53 GBytes  1.31 Gbits/sec  187             sender
[  4]   0.00-10.00  sec  1.53 GBytes  1.31 Gbits/sec                  receiver

iperf Done.

maybe we can debug your setup live tomorrow?

**Comment by gilesheron** [comment]
ah - my bad. that was on the local host.  I see the issue going over the network :(

xrvr@i2ss-c2201:~$ kubectl exec iperf3-clients-kx7d6 -- iperf3 -c 10.1.2.8 -p 5201
Connecting to host 10.1.2.8, port 5201
[  4] local 10.1.1.5 port 56150 connected to 10.1.2.8 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  84.8 KBytes   694 Kbits/sec    2   1.41 KBytes       
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  4]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  84.8 KBytes  69.5 Kbits/sec    5             sender
[  4]   0.00-10.00  sec  0.00 Bytes  0.00 bits/sec                  receiver

iperf Done.

but if I drop the MSS to 1400 bytes it works fine:

xrvr@i2ss-c2201:~$ kubectl exec iperf3-clients-kx7d6 -- iperf3 -V -M 1400 -c 10.1.2.8 -p 5201
iperf 3.0.7
Linux iperf3-clients-kx7d6 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 GNU/Linux
Time: Wed, 25 Jul 2018 18:07:13 GMT
Connecting to host 10.1.2.8, port 5201
      Cookie: iperf3-clients-kx7d6.1532542033.6070
      TCP MSS: 1400
[  4] local 10.1.1.5 port 57864 connected to 10.1.2.8 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   109 MBytes   912 Mbits/sec   93    842 KBytes       
[  4]   1.00-2.00   sec   109 MBytes   912 Mbits/sec    0    933 KBytes       
[  4]   2.00-3.00   sec   108 MBytes   902 Mbits/sec    0   1014 KBytes       
[  4]   3.00-4.00   sec   104 MBytes   870 Mbits/sec    0   1.06 MBytes       
[  4]   4.00-5.00   sec   106 MBytes   891 Mbits/sec  387    622 KBytes       
[  4]   5.00-6.00   sec   109 MBytes   912 Mbits/sec    0    741 KBytes       
[  4]   6.00-7.00   sec   109 MBytes   912 Mbits/sec    0    843 KBytes       
[  4]   7.00-8.00   sec   108 MBytes   902 Mbits/sec    0    934 KBytes       
[  4]   8.00-9.00   sec   105 MBytes   881 Mbits/sec  271    544 KBytes       
[  4]   9.00-10.00  sec   105 MBytes   881 Mbits/sec   57    549 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.04 GBytes   898 Mbits/sec  808             sender
[  4]   0.00-10.00  sec  1.04 GBytes   896 Mbits/sec                  receiver
CPU Utilization: local/sender 5.3% (0.2%u/5.1%s), remote/receiver 5.9% (0.3%u/5.6%s)

iperf Done.


ok - will dig into it here.

**Comment by gilesheron** [comment]
ok - had a chance to look at the issue here.  The problem was my Ethernet switch was configured with default 1500 byte IP MTU, but VPP was set to a 9K MTU on the GigE port.   The tap port has a 1500 byte MTU also, so then the 1448 byte TCP MSS becomes 1488 bytes of IP MTU but with VXLAN overhead that expands to 1538 bytes (one extra MAC header of 14 bytes plus 8 bytes each of VXLAN and UDP headers and 20 bytes of IPv4).   So my switch was seeing the packets as "giants".   I reconfigured the switch to support jumbo frames on the interconnect VLAN and the server-facing ports and all was AOK:

======
xrvr@i2ss-c2201:~$ kubectl exec iperf3-clients-kx7d6 -- iperf3 -V -c 10.1.2.8 -p 5201
iperf 3.0.7
Linux iperf3-clients-kx7d6 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 GNU/Linux
Time: Thu, 26 Jul 2018 12:26:52 GMT
Connecting to host 10.1.2.8, port 5201
      Cookie: iperf3-clients-kx7d6.1532608012.3495
      TCP MSS: 1448 (default)
[  4] local 10.1.1.5 port 60302 connected to 10.1.2.8 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   109 MBytes   918 Mbits/sec   37   1.21 MBytes       
[  4]   1.00-2.00   sec   106 MBytes   891 Mbits/sec    0   1.32 MBytes       
[  4]   2.00-3.00   sec   109 MBytes   912 Mbits/sec    0   1.41 MBytes       
[  4]   3.00-4.00   sec   104 MBytes   870 Mbits/sec  218   1.06 MBytes       
[  4]   4.00-5.00   sec   108 MBytes   902 Mbits/sec    0   1.13 MBytes       
[  4]   5.00-6.00   sec   109 MBytes   912 Mbits/sec    0   1.20 MBytes       
[  4]   6.00-7.00   sec   109 MBytes   912 Mbits/sec    0   1.27 MBytes       
[  4]   7.00-8.00   sec   109 MBytes   912 Mbits/sec    0   1.33 MBytes       
[  4]   8.00-9.00   sec   106 MBytes   891 Mbits/sec  137   1.04 MBytes       
[  4]   9.00-10.00  sec   106 MBytes   892 Mbits/sec    0   1.13 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.05 GBytes   901 Mbits/sec  392             sender
[  4]   0.00-10.00  sec  1.05 GBytes   900 Mbits/sec                  receiver
CPU Utilization: local/sender 5.5% (0.3%u/5.3%s), remote/receiver 1.1% (0.1%u/1.0%s)

iperf Done.
======

The default contiv-vpp.yaml sets MTU to 1500 bytes (see the MTUSize statement on line 29).  that seems to work for the tap interfaces but not for the loop0 or the GigE port (which are left at 9K).

If you can't reconfigure your Ethernet switches then you can modify the MTUSize in Contiv-VPP.yaml to 1450 bytes or less.

I did that here and reset my switches to 1500 byte MTUs and iperf3 now works fine (albeit it consumes slightly more CPU given the smaller packets):

======
xrvr@i2ss-c2201:~$ kubectl exec iperf3-clients-f2gml -- iperf3 -V -c 10.1.3.3 -p 5201
iperf 3.0.7
Linux iperf3-clients-f2gml 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 GNU/Linux
Time: Thu, 26 Jul 2018 13:59:45 GMT
Connecting to host 10.1.3.3, port 5201
      Cookie: iperf3-clients-f2gml.1532613585.9540
      TCP MSS: 1398 (default)
[  4] local 10.1.2.2 port 59554 connected to 10.1.3.3 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   109 MBytes   917 Mbits/sec   53   1.18 MBytes       
[  4]   1.00-2.00   sec   108 MBytes   902 Mbits/sec    0   1.29 MBytes       
[  4]   2.00-3.00   sec   108 MBytes   902 Mbits/sec    0   1.38 MBytes       
[  4]   3.00-4.00   sec   108 MBytes   902 Mbits/sec  483   1.01 MBytes       
[  4]   4.00-5.00   sec   108 MBytes   902 Mbits/sec    0   1.09 MBytes       
[  4]   5.00-6.00   sec   109 MBytes   912 Mbits/sec    0   1.15 MBytes       
[  4]   6.00-7.00   sec   105 MBytes   881 Mbits/sec    0   1.22 MBytes       
[  4]   7.00-8.00   sec   109 MBytes   912 Mbits/sec    0   1.28 MBytes       
[  4]   8.00-9.00   sec   108 MBytes   902 Mbits/sec  503    965 KBytes       
[  4]   9.00-10.00  sec   108 MBytes   902 Mbits/sec    0   1.06 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.05 GBytes   903 Mbits/sec  1039             sender
[  4]   0.00-10.00  sec  1.05 GBytes   902 Mbits/sec                  receiver
CPU Utilization: local/sender 5.8% (0.2%u/5.6%s), remote/receiver 4.1% (0.2%u/3.9%s)

iperf Done.
======

**Comment by gilesheron** [comment]
as an example of the benefits of increasing MTU see the below (where we get to 983 mbits/s instead of 903 simply by using larger MTUs):

xrvr@i2ss-c2201:~$ kubectl exec iperf3-clients-spj2q -- iperf3 -V -c 10.1.3.2 -p 5201
iperf 3.0.7
Linux iperf3-clients-spj2q 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 GNU/Linux
Time: Thu, 26 Jul 2018 14:11:25 GMT
Connecting to host 10.1.3.2, port 5201
      Cookie: iperf3-clients-spj2q.1532614284.8026
      TCP MSS: 8836 (default)
[  4] local 10.1.2.2 port 44690 connected to 10.1.3.2 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   118 MBytes   992 Mbits/sec   12   1.58 MBytes       
[  4]   1.00-2.00   sec   118 MBytes   986 Mbits/sec    1   1.35 MBytes       
[  4]   2.00-3.00   sec   118 MBytes   986 Mbits/sec    0   1.69 MBytes       
[  4]   3.00-4.00   sec   116 MBytes   975 Mbits/sec    1   1.47 MBytes       
[  4]   4.00-5.00   sec   118 MBytes   986 Mbits/sec    0   1.80 MBytes       
[  4]   5.00-6.00   sec   116 MBytes   975 Mbits/sec    4   1.59 MBytes       
[  4]   6.00-7.00   sec   118 MBytes   986 Mbits/sec    1   1.36 MBytes       
[  4]   7.00-8.00   sec   118 MBytes   986 Mbits/sec    0   1.70 MBytes       
[  4]   8.00-9.00   sec   116 MBytes   975 Mbits/sec    2   1.47 MBytes       
[  4]   9.00-10.00  sec   118 MBytes   986 Mbits/sec    0   1.80 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.14 GBytes   983 Mbits/sec   21             sender
[  4]   0.00-10.00  sec  1.14 GBytes   982 Mbits/sec                  receiver
CPU Utilization: local/sender 5.8% (0.2%u/5.6%s), remote/receiver 5.9% (0.3%u/5.6%s)

iperf Done.

**Comment by rastislavszabo** [comment]
Changing default MTU to 1450 in https://github.com/contiv/vpp/pull/959

**Comment by acloudiator** [comment]
@rastislavszabo 
Thanks for merging the fix!

@gilesheron 
Thanks for your findings! Have got two questions for you, if you don't mind.
1. Was this test a `pod to pod` or `host to Nodeport`. Please confirm.
2. What is your NIC capacity? 1 or 10 GbE? I will be trying this thing next week on 25 GbE NIC and share the results. I believe with MTU 1450, it should work for me as well.

**Comment by gilesheron** [comment]
This was pod to pod with GigE NICs (I have 3 rather ageing bare metal servers in the lab that I test with...)

**Comment by gilesheron** [comment]
oh - meant to say.  25GE NICs will be interesting - especially if you can change the MTU on your switch  to >= 9K and test e.g. the default 1450 bytes vs 8950 bytes.

**Comment by itaimlx** [comment]
hi Guys, 
I am getting ~2Gbits/sec over 100GB Mellanox NIC (between 2 bare metals connected back to back) - on Pod-to-Pod test.
```
# kubectl exec iperf3-clients-7cfff956b6-sjcpv -- /bin/sh -c 'iperf3 -c 10.1.1.5'
Connecting to host 10.1.1.5, port 5201
[  4] local 10.1.2.2 port 40514 connected to 10.1.1.5 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   221 MBytes  1.85 Gbits/sec  2072    167 KBytes
[  4]   1.00-2.00   sec   215 MBytes  1.80 Gbits/sec  2373    135 KBytes
[  4]   2.00-3.00   sec   213 MBytes  1.79 Gbits/sec  2045    190 KBytes
[  4]   3.00-4.00   sec   213 MBytes  1.79 Gbits/sec  2231    192 KBytes
[  4]   4.00-5.00   sec   217 MBytes  1.82 Gbits/sec  2689    120 KBytes
[  4]   5.00-6.00   sec   223 MBytes  1.87 Gbits/sec  2286    209 KBytes
[  4]   6.00-7.00   sec   231 MBytes  1.94 Gbits/sec  2944    251 KBytes
[  4]   7.00-8.00   sec   230 MBytes  1.93 Gbits/sec  2526    319 KBytes
[  4]   8.00-9.00   sec   219 MBytes  1.84 Gbits/sec  1925    135 KBytes
[  4]   9.00-10.00  sec   225 MBytes  1.88 Gbits/sec  2182    164 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  2.15 GBytes  1.85 Gbits/sec  23273             sender
[  4]   0.00-10.00  sec  2.15 GBytes  1.85 Gbits/sec                  receiver

iperf Done.
```
I would expect much better performance. any idea?
anyone tested with 25G intel NICs?

**Comment by rastislavszabo** [comment]
Hi @itaimlx ,

in the POD-to-POD setup, the main bottleneck is in the TAP interface between VPP and the POD, which goes via kernel. There are some improvements coming (implementation of Generic Segmentation Offload - GSO on VPP), but that will come later, with VPP 19.04.

To utilize your NIC, you may try scaling this up to several server PODs and several client PODs on each node. You can also use k8s service to load-balance between multiple server PODs - the load-balancing happens on VPP, so there shouldn't be any big performance drop.

Also, you may try tweaking MTUs, and if both nodes are on the same L2 subnet, disable VXLAN between the nodes using the `useL2Interconnect: true` (https://github.com/contiv/vpp/blob/master/k8s/contiv-vpp.yaml#L25).

**Comment by itaimlx** [comment]
@rastislavszabo - thanks for the quick reply! 
I also tried to increase the number of cores used by vpp without success (see #1432), but now I understand that it would not help in any case.

few more questions:
1. my nodes are connected back to back. is there a point tweaking MTUs?
2. I repeated the test with pure L2 (no vxlan) as you advised and got the same results
3. what did you mean in your comment above regarding measuring from POD (NOT with hostNetwrok==True)? were you referring to hostNetwrok vswitch parameter in contiv-vpp.yaml ?
4. does it make sense that same iperf test over contiv (ovs) data plane will give 11Gbits/s, and over contiv-vpp only 2Gbits/s? (https://community.mellanox.com/s/article/reference-deployment-guide-for-kubernetes-cluster-with-contiv-cni-plugin-over-mellanox-25gb-and-100gb-ethernet-solutions). both are   limited by kernel...

**Comment by rastislavszabo** [comment]
@itaimlx 
1. MTU - see https://github.com/contiv/vpp/blob/master/k8s/contiv-vpp.yaml#L33
2. yeah, might be, since the VXLAN encap (VPP) is not the bottleneck
3. I meant not setting `hostNetwork: true` for the PODs with the application (iperf in your case), not contiv PODs
4. yeah, if it is on exactly same setup & hardware, it would be interesting to dig into it. I would expect the same performance as well. Not sure if OVS uses GSO?
